### ISSUE TITLE
FPF.hs fehlt

### ISSUE THREAD

**Issue by RGiga4** [philippjan/PraktikumLogik#7]
Bei DP wird FPF import 
Eigentlich brauch ich, fpf als funkntion auch, aber was nicht da ist kann ich nicht importieren

**Comment by MarWeg** [comment]
Hatte wohl die falsche Datei hochgeladen. Korrigiere ich gleich noch. Statt FPF kann man auch Data.Map benutzen

**Comment by RGiga4** [comment]
funktioniert

**Comment by RGiga4** [comment]
funktioniert doch nicht, die Namen DavisPutnam und DP (und Putman) unterscheiden sich.
modul umbennnat zu DP
